In [3]:
import pandas as pd

# QualityMsr Cleaning

In [ ]:
# Load the files
def load_csv(filename):
    try:
        return pd.read_csv(filename, encoding="utf-8", low_memory=False)
    except UnicodeDecodeError:
          return pd.read_csv(filename, encoding="ISO-8859-1",low_memory=False)

# Function to standardize column names
def standardize_columns(df):
    df.columns = df.columns.str.lower().str.replace(' ','_')
    return df

quality_file_paths = [
    "QualityMsrMDS_2015.csv",
    "QualityMsrMDS_2016.csv",
    "QualityMsrMDS_2017.csv",
    "QualityMsrMDS_2018.csv",
    "QualityMsrMDS_2019.csv",
    "QualityMsrMDS_2020.csv",
    "QualityMsrMDS_2021.csv",
]

quality_dfs = {}

for file in quality_file_paths:
    year = file.split("_")[-1].split(".")[0] # Extract the year 
    df = load_csv(file)
    df = standardize_columns(df)
    quality_dfs[f"QualityMsrMDS_{year}"] = df

# print(quality_dfs["QualityMsrMDS_2020"].head())

In [ ]:
# Rename the column names in 2020 and 2021
column_mapping = { 
    'federal_provider_number': 'provnum',
    'measure_code': 'msr_cd',
    'measure_description': 'msr_descr',
    'resident_type': 'stay_type',
    'four_quarter_average_score': 'measure_score_4qtr_avg',
    'used_in_quality_measure_five_star_rating': 'five_star_msr'
}

quality_dfs["QualityMsrMDS_2020"] = quality_dfs["QualityMsrMDS_2020"].rename(columns=column_mapping)
quality_dfs["QualityMsrMDS_2021"] = quality_dfs["QualityMsrMDS_2021"].rename(columns=column_mapping)
# print(quality_dfs["QualityMsrMDS_2020"].head(5))
# print(quality_dfs["QualityMsrMDS_2021"].head(5))

In [ ]:
# Filtering out the chosen columns
quality_chosen_columns = [
    'provnum', "msr_cd", 'msr_descr', 'stay_type','q1_measure_score','q2_measure_score',
    'q3_measure_score','five_star_msr'
]

filtered_quality_dfs = {}

for year in range(2015, 2022):
    year_key = f"QualityMsrMDS_{year}"

    if year_key in quality_dfs:
        filtered_quality_dfs[year_key] = quality_dfs[year_key][quality_chosen_columns]
# print(filtered_quality_dfs["QualityMsrMDS_2020"].head())

In [ ]:
#Adding a year column
for year_key, df in filtered_quality_dfs.items():
    year = int(year_key.split('_')[-1])  # Get the year from the key
    df['year'] = year  
for year_key, df in filtered_quality_dfs.items():
    print(f"Displaying DataFrame for {year_key}:")
    # display(df.head(3))

In [ ]:
#Merging the files
QualityMeasure = pd.concat(filtered_quality_dfs.values(), ignore_index=True)
# display(QualityMeasure.head())

In [42]:
QualityMeasure.to_csv("QualityMeasure.csv", index=False)

# Penalties Cleaning

In [8]:
# Using the functions above, loading the files and loweringcase and stripping off the space for the column names
 def load_csv(filename):
    try:
        return pd.read_csv(filename, encoding="utf-8", low_memory=False)
    except UnicodeDecodeError:
          return pd.read_csv(filename, encoding="ISO-8859-1",low_memory=False)

# Function to standardize column names
def standardize_columns(df):
    df.columns = df.columns.str.lower().str.replace(' ','_')
    return df
    
penalties_file_paths = [
    "Penalties_2015.csv",
    "Penalties_2016.csv",
    "Penalties_2017.csv",
    "Penalties_2018.csv",
    "Penalties_2019.csv",
    "Penalties_2020.csv",
    "Penalties_2021.csv"
]

penalty_dfs = {}

for file in penalties_file_paths:
    year = file.split("_")[-1].split(".")[0]   
    df = load_csv(file)
    df = standardize_columns(df)
    penalty_dfs[f"Penalties_{year}"] = df

display(penalty_dfs["Penalties_2020"].head(3))

,federal_provider_number,provider_name,provider_address,provider_city,provider_state,provider_zip_code,penalty_date,penalty_type,fine_amount,payment_denial_start_date,payment_denial_length_in_days,location,processing_date
0,15015,PLANTATION MANOR NURSING HOME,6450 OLD TUSCALOOSA HIGHWAY P O BOX 97,MC CALLA,AL,35111,2018-04-19,Fine,22903.0,NaN,NaN,"6450 OLD TUSCALOOSA HIGHWAY P O BOX 97,MC CA...",2020-11-01
1,15015,PLANTATION MANOR NURSING HOME,6450 OLD TUSCALOOSA HIGHWAY P O BOX 97,MC CALLA,AL,35111,2019-05-02,Fine,6708.0,NaN,NaN,"6450 OLD TUSCALOOSA HIGHWAY P O BOX 97,MC CA...",2020-11-01
2,15019,MERRY WOOD LODGE,P O BOX 130,ELMORE,AL,36025,2019-03-02,Fine,78677.0,NaN,NaN,"P O BOX 130,ELMORE,AL,36025",2020-11-01

In [ ]:
# Rename the column names in 2020 and 2021
penalty_column_mapping = { 
    'federal_provider_number': 'provnum',
    'provider_name': 'provname',
    'provider_address': 'address',
    'provider_city': 'city',
    'provider_state': 'state',
    'provider_zip_code': 'zip',
    'penalty_date': 'pnlty_date',
    'penalty_type':'pnlty_type',
    'fine_amount': 'fine_amt',
}

penalty_dfs["Penalties_2020"] = penalty_dfs["Penalties_2020"].rename(columns=penalty_column_mapping)
penalty_dfs["Penalties_2021"] = penalty_dfs["Penalties_2021"].rename(columns=penalty_column_mapping)
# display(penalty_dfs["Penalties_2020"].head(5))
# display(penalty_dfs["Penalties_2021"].head(5))

In [12]:
# Filtering out the chosen columns
penalty_chosen_columns = [
    'provnum','pnlty_date','pnlty_type','fine_amt'
]

filtered_penalty_dfs = {}

for year in range(2015, 2022):
    year_key = f"Penalties_{year}"

    if year_key in penalty_dfs:
        filtered_penalty_dfs[year_key] = penalty_dfs[year_key][penalty_chosen_columns]
display(filtered_penalty_dfs["Penalties_2020"].head(3))

   provnum  pnlty_date pnlty_type  fine_amt
0    15015  2018-04-19       Fine   22903.0
1    15015  2019-05-02       Fine    6708.0
2    15019  2019-03-02       Fine   78677.0

In [ ]:
#Adding a year column
for year_key, df in filtered_penalty_dfs.items():
    year = int(year_key.split('_')[-1])  # Get the year from the key
    df['year'] = year  
for year_key, df in filtered_penalty_dfs.items():
    print(f"Displaying DataFrame for {year_key}:")
    # display(df.head(3))

In [14]:
#Merging the files
Penalty = pd.concat(filtered_penalty_dfs.values(), ignore_index=True)
display(Penalty.head())

  provnum  pnlty_date      pnlty_type  fine_amt  year
0   15019  2014-10-02            Fine    6692.0  2015
1   15037  2015-05-21            Fine   13813.0  2015
2   15053  2014-05-16            Fine  142870.0  2015
3   15053  2014-05-16  Payment Denial       NaN  2015
4   15060  2015-04-16            Fine   58273.0  2015

In [16]:
Penalty.to_csv("Penalties.csv",index=False)

# HD Cleaning

In [24]:
#List of file paths
HD_file_paths = [
    "HD2015.csv",
    "HD2016.csv",
    "HD2017.csv",
    "HD2018.csv",
    "HD2019.csv",
    "HD2020.csv",
    "HD2021.csv"
]

 
HD_dfs = {}

 
for file in HD_file_paths:
     
    year = file[-8:-4]   
    
    df = load_csv(file)
    df = standardize_columns(df)

     
    df['year'] = int(year)  
    
    HD_dfs[f"HD{year}"] = df

    

 
display(HD_dfs["HD2020"].head(3))

  provnum  sum_of_hd_code  count_of_hd_code  year
0   15009              12                 3  2020
1   15010              52                12  2020
2   15012              55                11  2020

In [25]:
print(HD_dfs.keys())

dict_keys(['HD2015', 'HD2016', 'HD2017', 'HD2018', 'HD2019', 'HD2020', 'HD2021'])

In [29]:
#Merging the files
HDs = pd.concat(HD_dfs.values(), ignore_index=True)
display(HDs.head())

  provnum  sum_of_hd_code  count_of_hd_code  year
0    1700             208                43  2015
1   15009              76                17  2015
2   15010             122                25  2015
3   15012              73                16  2015
4   15014             139                32  2015

In [32]:
HDs.to_csv("HDs.csv", index=False)

In [47]:
HDs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107516 entries, 0 to 107515
Data columns (total 4 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   provnum           107516 non-null  object
 1   sum_of_hd_code    107516 non-null  int64
 2   count_of_hd_code  107516 non-null  int64
 3   year              107516 non-null  int64
dtypes: int64(3), object(1)
memory usage: 3.3+ MB

In [52]:
CostReport = pd.read_csv(r"/Users/brandonnguyen/Desktop/ACE_Project/CostReport.csv", encoding="utf-8", low_memory=False)

In [66]:
CostReport = CostReport.rename(columns= {
                'rpt_rec_num' : 'reportNum',
                'provider_ccn': 'provnum'
})

In [ ]:
CostReport.info()
CostReport.sample()

In [71]:
ProviderInfo = pd.read_csv(r"/Users/brandonnguyen/Desktop/ACE_Project/ProviderInfo.csv", encoding="utf-8", low_memory=False)

In [82]:
CostReport.to_csv("CostReport.csv",index=False)

# Cost Report Cleaning

In [6]:
costReport_2015 = pd.read_csv(r"/Users/brandonnguyen/Desktop/ACE_Project/2015_CostReport.csv")

/var/folders/7t/7qf1whc969jcpbccjdpbv57r0000gn/T/ipykernel_20974/3944741479.py:1: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  costReport_2015 = pd.read_csv(r"/Users/brandonnguyen/Desktop/ACE_Project/2015_CostReport.csv")

In [8]:
def load_csv(filename):
    try:
        return pd.read_csv(filename, encoding="utf-8", low_memory=False)
    except UnicodeDecodeError:
          return pd.read_csv(filename, encoding="ISO-8859-1",low_memory=False)

# Function to standardize column names
def standardize_columns(df):
    df.columns = df.columns.str.lower().str.replace(' ','_')
    return df

In [9]:
costreport_file_paths = [
    "2015_CostReport.csv",
    "2016_CostReport.csv",
    "2017_CostReport.csv",
    "2018_CostReport.csv",
    "2019_CostReport.csv",
    "2020_CostReport.csv",
    "2021_CostReport.csv"
]

costreport_dfs = {}

for file in costreport_file_paths:
    year = file.split("_")[0]   
    df = load_csv(file)
    df = standardize_columns(df)
    costreport_dfs[f"{year}_CostReport"] = df
 display(costreport_dfs["2020_CostReport"].head(1))

,rpt_rec_num,provider_ccn,facility_name,street_address,city,state_code,zip_code,county,medicare_cbsa_number,rural_versus_urban,...,less_contractual_allowance_and_discounts_on_patients'_accounts,net_patient_revenue,less_total_operating_expense,net_income_from_service_to_patients,total_other_income,total_income,net_income,inpatient_pps_amount,nursing_and_allied_health_education_activities,allowable_bad_debts
0,1254744,75031,GLEN HILL CENTER,1 GLEN HILL ROAD,DANBURY,CT,06811,FAIRFIELD,14860.0,U,...,712087.0,1083396.0,1023062.0,60334.0,50.0,60384.0,60384.0,476754.0,NaN,4814.0

In [16]:
with pd.option_context('display.max_columns', None):
 display(costreport_dfs["2020_CostReport"].head(1))

,rpt_rec_num,provider_ccn,facility_name,street_address,city,state_code,zip_code,county,medicare_cbsa_number,rural_versus_urban,fiscal_year_begin_date,fiscal_year_end_date,type_of_control,total_days_title_v,total_days_title_xviii,total_days_title_xix,total_days_other,total_days_total,number_of_beds,total_bed_days_available,total_discharges_title_v,total_discharges_title_xviii,total_discharges_title_xix,total_discharges_title_other,total_discharges_total,snf_average_length_of_stay_title_v,snf_average_length_of_stay_title_xviii,snf_average_length_of_stay_title_xix,snf_average_length_of_stay_total,snf_admissions_title_v,snf_admissions_title_xviii,snf_admissions_title_xix,snf_admissions_other,snf_admissions_total,snf_days_title_v,snf_days_title_xviii,snf_days_title_xix,snf_days_other,snf_days_total,snf_number_of_beds,snf_bed_days_available,snf_discharges_title_v,snf_discharges_title_xviii,snf_discharges_title_xix,snf_discharges_title_other,snf_discharges_total,nf_number_of_beds,nf_bed_days_available,nf_days_title_v,nf_days_title_xix,nf_days_other,nf_days_total,nf_discharges_title_v,nf_discharges_title_xix,nf_discharges_title_other,nf_discharges_total,nf_average_length_of_stay_title_v,nf_average_length_of_stay_title_xix,nf_average_length_of_stay_total,nf_admissions_title_v,nf_admissions_title_xix,nf_admissions_other,nf_admissions_total,total_rug_days,total_salaries_from_worksheet_a,overhead_non-salary_costs,total_charges,total_costs,wage-related_costs_(core),total_salaries_(adjusted),contract_labor,cash_on_hand_and_in_banks,temporary_investments,notes_receivable,accounts_receivable,less:_allowances_for_uncollectible_notes_and_accounts_receivable,inventory,prepaid_expenses,other_current_assets,total_current_assets,land,land_improvements,buildings,leasehold_improvements,fixed_equipment,major_movable_equipment,minor_equipment_depreciable,total_fixed_assets,investments,other_assets,total_other_assets,total_assets,accounts_payable,"salaries,_wages,_and_fees_payable",payroll_taxes_payable,notes_and_loans_payable_(short_term),deferred_income,other_current_liabilities,total_current_liabilities,mortgage_payable,notes_payable,unsecured_loans,other_long_term_liabilities,total_long_term_liabilities,total_liabilities,general_fund_balance,total_fund_balances,total_liabilities_and_fund_balances,total_general_inpatient_care_services_revenue,inpatient_revenue,outpatient_revenue,gross_revenue,less_contractual_allowance_and_discounts_on_patients'_accounts,net_patient_revenue,less_total_operating_expense,net_income_from_service_to_patients,total_other_income,total_income,net_income,inpatient_pps_amount,nursing_and_allied_health_education_activities,allowable_bad_debts
0,1254744,75031,GLEN HILL CENTER,1 GLEN HILL ROAD,DANBURY,CT,06811,FAIRFIELD,14860.0,U,10/01/2019,10/31/2019,6.0,NaN,735.0,1648.0,538.0,2921.0,100.0,3100.0,NaN,24.0,8.0,25.0,57.0,NaN,30.63,206.0,51.25,NaN,27.0,2.0,29.0,58.0,NaN,735.0,1648.0,538.0,2921.0,100.0,3100.0,NaN,24.0,8.0,25.0,57.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,371857.0,651205.0,299558.0,195203.0,79053.0,371857.0,136024.0,15647.0,NaN,NaN,1223466.0,135613.0,65289.0,24359.0,NaN,1284327.0,NaN,518.0,NaN,10688.0,3374.0,17985.0,NaN,35976.0,NaN,13080009.0,13080009.0,14400312.0,493549.0,259658.0,NaN,566616.0,43323.0,146013.0,1509159.0,8194774.0,NaN,NaN,NaN,8194774.0,9703933.0,4696379.0,4696379.0,14400312.0,1490851.0,1795483.0,NaN,1795483.0,712087.0,1083396.0,1023062.0,60334.0,50.0,60384.0,60384.0,476754.0,NaN,4814.0

In [25]:
#Rename the column names in 2020 and 2021 to match with 2015 to 2019
 
rename_map_2020_2021 = {
    'salaries,_wages,_and_fees_payable': 'salaries_wages_and_fees_payable',
    'total_liabilities_and_fund_balances': 'total_liab_and_fund_balances',
    'total_salaries_(adjusted)': 'total_salaries_adjusted'
}

# Apply to 2020 and 2021 DataFrames
for year in ["2020", "2021"]:
    key = f"{year}_CostReport"
    if key in costreport_dfs:
        costreport_dfs[key] = costreport_dfs[key].rename(columns=rename_map_2020_2021)

In [27]:
# Filtering out the chosen columns
costreport_chosen_columns = [
    'rpt_rec_num', 'provider_ccn',
    'rural_versus_urban','fiscal_year_begin_date',
    'fiscal_year_end_date','gross_revenue','inpatient_revenue',
    'net_income','net_patient_revenue','number_of_beds','total_assets',
    'total_bed_days_available','total_costs','total_discharges_total','total_income',
    'total_liabilities', 'less_total_operating_expense',
    'salaries_wages_and_fees_payable',         # ← FIXED
    'total_liab_and_fund_balances',
    'total_salaries_adjusted',                 # ← FIXED
    'total_fund_balances'
]

filtered_costreport_dfs = {}

for year in range(2015, 2022):
    year_key = f"{year}_CostReport"

    if year_key in costreport_dfs:
        filtered_costreport_dfs[year_key] = costreport_dfs[year_key][costreport_chosen_columns]
display(filtered_costreport_dfs["2020_CostReport"].head(1))

,rpt_rec_num,provider_ccn,rural_versus_urban,fiscal_year_begin_date,fiscal_year_end_date,gross_revenue,inpatient_revenue,net_income,net_patient_revenue,number_of_beds,...,total_bed_days_available,total_costs,total_discharges_total,total_income,total_liabilities,less_total_operating_expense,salaries_wages_and_fees_payable,total_liab_and_fund_balances,total_salaries_adjusted,total_fund_balances
0,1254744,75031,U,10/01/2019,10/31/2019,1795483.0,1795483.0,60384.0,1083396.0,100.0,...,3100.0,195203.0,57.0,60384.0,9703933.0,1023062.0,259658.0,14400312.0,371857.0,4696379.0

In [ ]:
#Adding a year column
for year_key, df in filtered_costreport_dfs.items():
    year = int(year_key.split('_')[0])  # Get the year from the key
    df['year'] = year  
for year_key, df in filtered_costreport_dfs.items():
    print(f"Displaying DataFrame for {year_key}:")
     display(df.head(1))

In [32]:
#Merging the files
CostReport = pd.concat(filtered_costreport_dfs.values(), ignore_index=True)
display(CostReport.head())

,rpt_rec_num,provider_ccn,rural_versus_urban,fiscal_year_begin_date,fiscal_year_end_date,gross_revenue,inpatient_revenue,net_income,net_patient_revenue,number_of_beds,...,total_costs,total_discharges_total,total_income,total_liabilities,less_total_operating_expense,salaries_wages_and_fees_payable,total_liab_and_fund_balances,total_salaries_adjusted,total_fund_balances,year
0,1089712,495134,U,11/1/2014,12/31/2014,1800296.0,1800296.0,311430.0,1520630.0,120.0,...,211585.0,49.0,311431.0,453590.0,1209322.0,117929.0,765020.0,660232.0,311430.0,2015
1,1091410,75417,U,10/1/2014,12/14/2014,2843541.0,2843541.0,-588469.0,2416825.0,114.0,...,207903.0,59.0,-588469.0,6584403.0,3005301.0,12590.0,1687456.0,1118860.0,-4896947.0,2015
2,1093283,165252,R,10/1/2014,12/31/2014,613243.0,613243.0,-47859.0,600033.0,60.0,...,22920.0,9.0,-30743.0,192098.0,639168.0,48546.0,244239.0,348614.0,52141.0,2015
3,1095547,225497,U,11/1/2014,12/31/2014,1935277.0,1935277.0,-63638.0,1378163.0,141.0,...,158386.0,32.0,-63638.0,1824376.0,1444469.0,201598.0,1830758.0,601118.0,6382.0,2015
4,1095966,265161,U,12/1/2014,12/31/2014,818175.0,818175.0,-1613.0,769155.0,172.0,...,56556.0,28.0,-1613.0,808822.0,775242.0,258540.0,807209.0,363088.0,-1613.0,2015

In [33]:
CostReport.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106269 entries, 0 to 106268
Data columns (total 22 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   rpt_rec_num                      106269 non-null  int64
 1   provider_ccn                     106269 non-null  int64
 2   rural_versus_urban               104082 non-null  object
 3   fiscal_year_begin_date           104197 non-null  object
 4   fiscal_year_end_date             104197 non-null  object
 5   gross_revenue                    103986 non-null  float64
 6   inpatient_revenue                103985 non-null  float64
 7   net_income                       103909 non-null  float64
 8   net_patient_revenue              103990 non-null  float64
 9   number_of_beds                   103867 non-null  float64
 10  total_assets                     103490 non-null  float64
 11  total_bed_days_available         103860 non-null  float64
 12  total_costs                      104131 non-null  float64
 13  total_discharges_total           103912 non-null  float64
 14  total_income                     103961 non-null  float64
 15  total_liabilities                103252 non-null  float64
 16  less_total_operating_expense     104195 non-null  float64
 17  salaries_wages_and_fees_payable  95009 non-null   float64
 18  total_liab_and_fund_balances     104079 non-null  float64
 19  total_salaries_adjusted          104196 non-null  float64
 20  total_fund_balances              103835 non-null  float64
 21  year                             106269 non-null  int64
dtypes: float64(16), int64(3), object(3)
memory usage: 17.8+ MB

In [34]:
# Convert these columns to string
string_cols = ['provider_ccn', 'rpt_rec_num']
for col in string_cols:
    CostReport[col] = CostReport[col].astype(str)

# Convert these columns to datetime
date_cols = ['fiscal_year_begin_date', 'fiscal_year_end_date']
for col in date_cols:
    CostReport[col] = pd.to_datetime(CostReport[col], errors='coerce')

In [35]:
CostReport = CostReport.rename(columns={'provider_ccn': 'provnum'})
CostReport = CostReport.rename(columns={'rpt_rec_num': 'reportnum'})
CostReport.head(1)

,reportnum,provnum,rural_versus_urban,fiscal_year_begin_date,fiscal_year_end_date,gross_revenue,inpatient_revenue,net_income,net_patient_revenue,number_of_beds,...,total_costs,total_discharges_total,total_income,total_liabilities,less_total_operating_expense,salaries_wages_and_fees_payable,total_liab_and_fund_balances,total_salaries_adjusted,total_fund_balances,year
0,1089712,495134,U,2014-11-01,2014-12-31,1800296.0,1800296.0,311430.0,1520630.0,120.0,...,211585.0,49.0,311431.0,453590.0,1209322.0,117929.0,765020.0,660232.0,311430.0,2015

In [36]:
CostReport.to_csv("CostReport.csv", index=False)

# ProviderInfo Cleaning

In [37]:
ProviderInfo = pd.read_csv(r"/Users/brandonnguyen/Desktop/ACE_Project/ProviderInfo.csv")

In [38]:
ProviderInfo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108587 entries, 0 to 108586
Data columns (total 14 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   provnum          108587 non-null  object
 1   provname         108587 non-null  object
 2   address          108587 non-null  object
 3   city             108587 non-null  object
 4   state            108587 non-null  object
 5   zip              108587 non-null  int64
 6   ownership        108585 non-null  object
 7   restot           107344 non-null  float64
 8   overall_rating   107232 non-null  float64
 9   survey_rating    107232 non-null  float64
 10  quality_rating   107043 non-null  float64
 11  staffing_rating  105009 non-null  float64
 12  adj_total        103524 non-null  float64
 13  year             108587 non-null  int64
dtypes: float64(6), int64(2), object(6)
memory usage: 11.6+ MB

# Merging ProviderInfo with CostReport

In [39]:
# Make sure the data type for provnum is char(6)
ProviderInfo['provnum'] = ProviderInfo['provnum'].astype(str).str.zfill(6)
CostReport['provnum'] = CostReport['provnum'].astype(str).str.zfill(6)

In [40]:
nursing_home_data = ProviderInfo.merge(CostReport, 
                                          left_on=['provnum', 'year'], 
                                          right_on=['provnum', 'year'], 
                                          how='right')
# nursing_home_data.info()

In [ ]:
 
 nursing_home_data[nursing_home_data['provnum']=='075423'].info()

# Merge HDs with nursing_home_data

In [ ]:
HDs['provnum'] = HDs['provnum'].astype(str).str.zfill(6)

In [297]:
nursing_home_data = nursing_home_data.merge(HDs,
                                            left_on=['provnum','year'],
                                            right_on=['provnum','year'],
                                            how='left')

In [298]:
nursing_home_data.sample(1)

,provnum,provname,address,city,state,zip,ownership,restot,overall_rating,survey_rating,quality_rating,staffing_rating,adj_total,year,reportnum,rural_versus_urban,fiscal_year_begin_date,fiscal_year_end_date,gross_revenue,inpatient_revenue,net_income,net_patient_revenue,number_of_beds,total_assets,total_bed_days_available,total_costs,total_discharges_total,total_income,total_liabilities,sum_of_hd_code,count_of_hd_code
61260,035183,RIO VISTA POST ACUTE AND REHABILITATION,10323 WEST OLIVE AVENUE,PEORIA,AZ,85345.0,Non profit - Corporation,84.4,1.0,1.0,3.0,3.0,3.77337,2019,1244770,U,2019-01-01,2019-04-30,3330692.0,3330692.0,92693.0,2558104.0,150.0,7098424.0,18000.0,186385.0,169.0,101774.0,1423380.0,173.0,36.0

In [340]:
nursing_home_data['provnum'] = nursing_home_data['provnum'].astype(str).str.zfill(6)

# Annualize the data in cost report

In [43]:
nursing_home_data['fiscal_period'] = (
    nursing_home_data['fiscal_year_end_date'] - nursing_home_data['fiscal_year_begin_date']
).dt.days

In [44]:
 nursing_home_data.head(1)

,provnum,provname,address,city,state,zip,ownership,restot,overall_rating,survey_rating,...,total_costs,total_discharges_total,total_income,total_liabilities,less_total_operating_expense,salaries_wages_and_fees_payable,total_liab_and_fund_balances,total_salaries_adjusted,total_fund_balances,fiscal_period
0,495134,RIDGECREST MANOR NURSING & REHABILITATION,157 ROSS CARTER BOULEVARD,DUFFIELD,VA,24244.0,For profit - Corporation,102.0,1.0,1.0,...,211585.0,49.0,311431.0,453590.0,1209322.0,117929.0,765020.0,660232.0,311430.0,60.0

In [45]:
columns_to_annualize = [
    'gross_revenue', 'inpatient_revenue', 'net_income', 'net_patient_revenue',
    'total_assets', 'total_costs', 'total_income', 'total_liabilities'
]

for col in columns_to_annualize:
    nursing_home_data[f'annualized_{col}'] = (
        nursing_home_data[col] / nursing_home_data['fiscal_period'] * 365
    )

In [ ]:
nursing_home_data.info()

In [52]:
# Drop duplicates
nursing_home_data = nursing_home_data.drop_duplicates()

In [306]:
nursing_home_data.to_csv("nursing_home_data.csv",index=False)

# Filling missing values

In [53]:
#Check how many null values are in there before filling
nursing_home_data['provname'].isna().sum()

np.int64(530)

In [54]:
pd.set_option('display.max_columns', None)

In [ ]:
def backfill_provider_info(df):
    """
    Backfills missing provider information using the most recent non-null values 
    for the same provider (provnum) across multiple years.

    Args:
        df (pd.DataFrame): Input dataframe with provider records (multiple years).

    Returns:
        pd.DataFrame: DataFrame with missing provider information backfilled.
    """
    df = df.copy()
    provider_cols = ['provname', 'address', 'city', 'state', 'zip', 'ownership']

    df_sorted = df.sort_values(by=['provnum', 'year'])

    df_filled = df_sorted.groupby('provnum')[provider_cols].ffill()

    df[provider_cols] = df_filled
    
    return df

nursing_home_data_filled = backfill_provider_info(nursing_home_data)

 # Check the result
print(nursing_home_data_filled.head())

In [57]:
 # Check missing values after backfilling
provider_cols = ['provname']
print(nursing_home_data_filled[provider_cols].isna().sum())

provname    136
dtype: int64

In [59]:
nursing_home_data_filled.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106269 entries, 0 to 106268
Data columns (total 43 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   provnum                          106269 non-null  object
 1   provname                         106133 non-null  object
 2   address                          106133 non-null  object
 3   city                             106133 non-null  object
 4   state                            106133 non-null  object
 5   zip                              106133 non-null  float64
 6   ownership                        106133 non-null  object
 7   restot                           104771 non-null  float64
 8   overall_rating                   104444 non-null  float64
 9   survey_rating                    104444 non-null  float64
 10  quality_rating                   104355 non-null  float64
 11  staffing_rating                  102682 non-null  float64
 12  adj_total                        101470 non-null  float64
 13  year                             106269 non-null  int64
 14  reportnum                        106269 non-null  object
 15  rural_versus_urban               104082 non-null  object
 16  fiscal_year_begin_date           104197 non-null  datetime64[ns]
 17  fiscal_year_end_date             104197 non-null  datetime64[ns]
 18  gross_revenue                    103986 non-null  float64
 19  inpatient_revenue                103985 non-null  float64
 20  net_income                       103909 non-null  float64
 21  net_patient_revenue              103990 non-null  float64
 22  number_of_beds                   103867 non-null  float64
 23  total_assets                     103490 non-null  float64
 24  total_bed_days_available         103860 non-null  float64
 25  total_costs                      104131 non-null  float64
 26  total_discharges_total           103912 non-null  float64
 27  total_income                     103961 non-null  float64
 28  total_liabilities                103252 non-null  float64
 29  less_total_operating_expense     104195 non-null  float64
 30  salaries_wages_and_fees_payable  95009 non-null   float64
 31  total_liab_and_fund_balances     104079 non-null  float64
 32  total_salaries_adjusted          104196 non-null  float64
 33  total_fund_balances              103835 non-null  float64
 34  fiscal_period                    104197 non-null  float64
 35  annualized_gross_revenue         103986 non-null  float64
 36  annualized_inpatient_revenue     103985 non-null  float64
 37  annualized_net_income            103909 non-null  float64
 38  annualized_net_patient_revenue   103990 non-null  float64
 39  annualized_total_assets          103490 non-null  float64
 40  annualized_total_costs           104131 non-null  float64
 41  annualized_total_income          103961 non-null  float64
 42  annualized_total_liabilities     103252 non-null  float64
dtypes: datetime64[ns](2), float64(32), int64(1), object(8)
memory usage: 34.9+ MB

# Consolidate the providers who have multiple fiscal periods in a year

In [61]:
import numpy as np

def consolidate_annual_reports(df: pd.DataFrame) -> pd.DataFrame:
    # Filter out invalid fiscal periods
    df_valid = df[df['fiscal_period'] > 0].copy()
    
    # Identify annualized columns (those starting with 'annualized_')
    annualized_cols = [col for col in df_valid.columns if col.startswith('annualized_')]

    # Choose static fields you want to retain (e.g., provname, address, etc.)
    static_cols = ['provname', 'address', 'city', 'state', 'zip', 'ownership']

    # Optional: columns like restot, ratings, etc. can also be averaged or first taken
    other_cols = ['restot', 'overall_rating', 'survey_rating', 'quality_rating', 
                  'staffing_rating', 'adj_total', 'rural_versus_urban', 'number_of_beds',
                  'total_bed_days_available', 'total_discharges_total', 'less_total_operating_expense',
                  'salaries_wages_and_fees_payable', 'total_liab_and_fund_balances', 'total_salaries_adjusted',
                  'total_fund_balances'
                 ]

    # Define aggregation logic
    agg_dict = {col: 'first' for col in static_cols + other_cols}
    agg_dict.update({col: 'mean' for col in annualized_cols})

    # Add year to groupby
    grouped = df_valid.groupby(['provnum', 'year']).agg(agg_dict).reset_index()

    return grouped

In [62]:
annualized_nursing_data = consolidate_annual_reports(nursing_home_data_filled)

In [67]:
#Check info
annualized_nursing_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99386 entries, 0 to 99385
Data columns (total 31 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   provnum                          99386 non-null  object
 1   year                             99386 non-null  int64
 2   provname                         99303 non-null  object
 3   address                          99303 non-null  object
 4   city                             99303 non-null  object
 5   state                            99303 non-null  object
 6   zip                              99303 non-null  float64
 7   ownership                        99303 non-null  object
 8   restot                           98183 non-null  float64
 9   overall_rating                   97931 non-null  float64
 10  survey_rating                    97931 non-null  float64
 11  quality_rating                   97883 non-null  float64
 12  staffing_rating                  96357 non-null  float64
 13  adj_total                        95356 non-null  float64
 14  rural_versus_urban               99279 non-null  object
 15  number_of_beds                   99074 non-null  float64
 16  total_bed_days_available         99067 non-null  float64
 17  total_discharges_total           99131 non-null  float64
 18  less_total_operating_expense     99384 non-null  float64
 19  salaries_wages_and_fees_payable  91126 non-null  float64
 20  total_liab_and_fund_balances     99277 non-null  float64
 21  total_salaries_adjusted          99385 non-null  float64
 22  total_fund_balances              99074 non-null  float64
 23  annualized_gross_revenue         99209 non-null  float64
 24  annualized_inpatient_revenue     99209 non-null  float64
 25  annualized_net_income            99142 non-null  float64
 26  annualized_net_patient_revenue   99213 non-null  float64
 27  annualized_total_assets          98726 non-null  float64
 28  annualized_total_costs           99328 non-null  float64
 29  annualized_total_income          99185 non-null  float64
 30  annualized_total_liabilities     98513 non-null  float64
dtypes: float64(23), int64(1), object(7)
memory usage: 23.5+ MB

In [68]:
# Check for unmatched rows by 'provnum' ( According to Nhien)
unmatched_rows = annualized_nursing_data[annualized_nursing_data['address'].isnull()]
unmatched_count = unmatched_rows.shape[0]
print(f"Total rows with unmatched 'provname': {unmatched_count}")

Total rows with unmatched 'provname': 83

In [69]:
annualized_nursing_data = annualized_nursing_data[~annualized_nursing_data['address'].isnull()]

In [70]:
annualized_nursing_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99303 entries, 0 to 99385
Data columns (total 31 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   provnum                          99303 non-null  object
 1   year                             99303 non-null  int64
 2   provname                         99303 non-null  object
 3   address                          99303 non-null  object
 4   city                             99303 non-null  object
 5   state                            99303 non-null  object
 6   zip                              99303 non-null  float64
 7   ownership                        99303 non-null  object
 8   restot                           98183 non-null  float64
 9   overall_rating                   97931 non-null  float64
 10  survey_rating                    97931 non-null  float64
 11  quality_rating                   97883 non-null  float64
 12  staffing_rating                  96357 non-null  float64
 13  adj_total                        95356 non-null  float64
 14  rural_versus_urban               99196 non-null  object
 15  number_of_beds                   98992 non-null  float64
 16  total_bed_days_available         98985 non-null  float64
 17  total_discharges_total           99048 non-null  float64
 18  less_total_operating_expense     99301 non-null  float64
 19  salaries_wages_and_fees_payable  91055 non-null  float64
 20  total_liab_and_fund_balances     99195 non-null  float64
 21  total_salaries_adjusted          99302 non-null  float64
 22  total_fund_balances              98992 non-null  float64
 23  annualized_gross_revenue         99126 non-null  float64
 24  annualized_inpatient_revenue     99126 non-null  float64
 25  annualized_net_income            99059 non-null  float64
 26  annualized_net_patient_revenue   99130 non-null  float64
 27  annualized_total_assets          98644 non-null  float64
 28  annualized_total_costs           99245 non-null  float64
 29  annualized_total_income          99102 non-null  float64
 30  annualized_total_liabilities     98431 non-null  float64
dtypes: float64(23), int64(1), object(7)
memory usage: 24.2+ MB

In [71]:
# Export to csv
annualized_nursing_data.to_csv("Clean_nursing_data.csv",index=False)